### ISSUE TITLE
Create new stable release version to support wider use

### ISSUE THREAD

**Issue by christopher-hopper** [DealerDirect/phpcodesniffer-composer-installer#11]
## Problem/Motivation

Now we've extended support for existing packages that use a slightly deeper folder structure, I'm keen to see a new version number bump soon. Some projects do not like using `dev-master` version constraints and set Composer minimum stability to prevent `@dev` or `dev-master` versions from being used.

This would help me with getting the Drupal Coder maintainers to adopt your installer plugin for official use with their existing package.

## Expected behaviour

The plugin works with packages like drupal/coder when minimum stability is set to stable.

## Actual behaviour

Currently minimum stability must be set to `dev` in order to use this installer with some packages.

## Proposed changes

Bump a new release version soon.

**Comment by christopher-hopper** [comment]
This is the issue I have open currently with the Drupal Coder project maintainers, asking them to make a change that would support use of your excellent plugin:

- [Drupal Coder issue 2848532](https://www.drupal.org/node/2848532#comment-11920051)

**Comment by frenck** [comment]
Hi @christopher-hopper, thank you for your issues.

I want to include #5 into the next release and maybe even some CI / QA assurance.

The currently timeframe is set to release a new version this week. Thank you for your patience.

**Comment by christopher-hopper** [comment]
Sounds good. Thanks again for supporting collaboration on the project.

**Comment by frenck** [comment]
@christopher-hopper v0.3.0 has been released.

This fulfils the request in this issue, therefor closing it.
