### ISSUE TITLE
Switch from Travis CI .org to .com

### ISSUE THREAD

**Issue by jrfnl** [Dealerdirect/phpcodesniffer-composer-installer#112]
## Problem/Motivation

It looks like Travis is slowly closing down their old interface. I have seen a number of repos running into issues with Travis not reporting back on branches/pull requests anymore.

This does not (yet) seem to be the case for this repo, but I think pre-empting this would be a good thing™.

I don't have the authorization to make the necessary changes myself, so I'd like to ask the powers that be to make them. @mjrider Have you got access ?

Based on my experiences with other repos, this is what needs to happen:

> How to get TravisCI working again if it's currently not reporting:
> 1. On GitHub/ repo Settings: Remove the Webhook integration.
> 2. On GitHub/ marketplace: Install the Travis GH App
> 3. On travis-ci.com: sign up for the migrations beta for the organisation
> 4. On travis-ci.com: migrate all relevant repos
> 5. If this hasn't been done before PRs start failing to report back: Force push problem PRs
> 6. Once a first build has finished under the new system, change the protected branches to require "Travis CI - Pull Request" and un-require "continuous integration"

Source: https://twitter.com/jrf_nl/status/1255854838597984262

**Comment by mjrider** [comment]
Working on this right now

**Comment by mjrider** [comment]
done

**Comment by jrfnl** [comment]
Thanks @mjrider !
