### ISSUE TITLE
Fails to set installed_paths config on Composer 2.0.5

### ISSUE THREAD

**Issue by swiffer** [Dealerdirect/phpcodesniffer-composer-installer#120]
## Problem/Motivation

After upgrading to Composer 2.0.5 running `composer update` fails, because the plugin fails to set the installed_path config

## Expected behaviour

should run fine

## Actual behaviour

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)
>
> (Please include any relevant links. Think: links to a branch in a repo where you are experiencing the problem
> which can be used to reproduce the issue, links to external standards you are using.)
> (Also, if relevant and if it can be used to reproduce the issue, please paste the contents of your `composer.json`
> file here.
>
> ```json
> (Content of the `composer.json` file)
> ```

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

## Environment

| Question               | Answer
| ------------------------| -------
| OS                                | Windows/Linux/Mac (preferably with some version info)
| PHP version                       | x.y.z
| Composer version                  | x.y.z
| PHP_CodeSniffer version           | x.y.z
| Dealerdirect PHPCS plugin version | x.y.z
| Install type                      | e.g. Composer global, Composer project local, other (please expand)

Output of `vendor/bin/phpcs --config-show`:
```
(Please paste the output you get here)
```

## Tested against `master` branch?
- [ ] I have verified the issue still exists in the `master` branch.

**Comment by jrfnl** [comment]
@swiffer I've just tested with Composer 2.0.5 and cannot reproduce the issue.

I did notice some other oddities with Composer 2.0.5, but those are unrelated to this plugin.

Please fill in the issue template completely. As things are, your issue is not reproducable and therefore not actionable.
Without further information, this issue will be closed in 24 hours.

**Comment by jrfnl** [comment]
P.S.: [Composer 2.0.6](https://github.com/composer/composer/releases/tag/2.0.6) was just released. The other oddities I saw when testing appear to be solved now, so you may want to try to run `composer self-update` and then `composer update` again to see if that solved the issue you were having.

**Comment by swiffer** [comment]
it's fixed by updating to 2.0.6. at least i cannot reproduce this anymore. thanks!

**Comment by jrfnl** [comment]
@swiffer Glad to hear it and thanks for letting us know.
