### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by frenck** [DealerDirect/phpcodesniffer-composer-installer#17]
## Problem/Motivation

To make it easier for users and contributors to see precisely what notable changes have been made between each release (or version) of the project, a changlog should be added.

## Expected behaviour / Actual behaviour / Steps to reproduce

_Does not apply_

## Proposed changes

Add a changelog file to the root of this repository, using the format specified in the [Keep a CHANGELOG](http://keepachangelog.com/en/0.3.0/) documentation.

**Comment by Potherca** [comment]
I've been using [skywinder/Github-Changelog-Generator](https://github.com/skywinder/Github-Changelog-Generator) and at first sight it looks good.

There might be some minor points for improvement, but I'm sure we could open some PRs (or maintain a corporate fork) to tweak it for our own use...

**Comment by Wirone** [comment]
Guys, do you know http://keepachangelog.com/ ?

**Comment by Potherca** [comment]
Yes, we do :smile_cat:  [skywinder/Github-Changelog-Generator](https://github.com/skywinder/Github-Changelog-Generator) is keepachangelog.com compatible.

**Comment by frenck** [comment]
We currently already use the output of it in the GitHub releases descriptions of this repository.

https://github.com/DealerDirect/phpcodesniffer-composer-installer/releases

**Comment by Wirone** [comment]
@Potherca Oh, I missed that part in description (shame on me). I must check `skywinder/Github-Changelog-Generator` in that case :-)

**Comment by frenck** [comment]
I've discussed this today with @Potherca and @brammittendorff-dd in person.

Some time ago we already started keeping a change log between releases in the [GitHub releases section of this repository](https://github.com/DealerDirect/phpcodesniffer-composer-installer/releases).

Keeping a second change log inside the repo seems duplicate and causes extra overhead in the review process. Secondly; the GitHub releases interface, combined with change logs we place there, gives a much easier en feature rich way to analyse thinks, since you can click on everything.

We do agree we should tell people where to find the change logs, so we will be adding documentation and links in the README.

**Comment by frenck** [comment]
Added references to the changelogs in #31. Closing this issue.
