### ISSUE TITLE
Check the root package for sniffs to install

### ISSUE THREAD

**Issue by Potherca** [DealerDirect/phpcodesniffer-composer-installer#20]
## Problem/Motivation

As described in #19, the installer does not look in the root package. As it is completely viable for root packages to contain a code sniff, the installer should also check the root package.

## Expected behaviour / Actual behaviour / Steps to reproduce

_Not applicable._

## Proposed changes

A separate step needs to be implemented that checks the root package to see if it contains any sniffs that (also) need installing.

**Comment by frenck** [comment]
Added this feature in PR #25 and is waiting code review.

**Comment by frenck** [comment]
Merged into the master branch and will in the next release.
