### ISSUE TITLE
Installing coding standards when executing Composer with --no-scripts

### ISSUE THREAD

**Issue by Wirone** [DealerDirect/phpcodesniffer-composer-installer#4]
I've successfully integrated your installer and `frenck/php-compatibility` in Symfony application and it works on my localhost. However, when I want to use Gitlab CI it fails, because:
- we use `incenteev/composer-parameter-handler` for semi-automatic parameters configuration and few of them need to be set in order to work (Gitlab CI works in non-interactive mode and takes all parameters from dist file into final parameters file). Of course I can mock them in dist file, as a workaround
- running with `--no-scripts` will not trigger parameters handler and other (e.g. cache clearing) but also will not trigger installing PHPCompatibility rule set, so running `phpcs` will fail due `Referenced sniff "PHPCompatibility" does not exist` error

Is there possibility to run some custom Composer command/script and just install PHPCS plugins, without calling other scripts?

Do you have any suggestions how it should be configured and handled?

**Comment by Potherca** [comment]
Good to hear you have gotten things to work!

![](https://dealerdirect.github.io/Achievements/img/badges/png/badge_thumb.png)

In regards to your question, I'm not entirely sure I understand your current situation. 

Am I correct in assuming your `composer.json` looks something similar to the example below?

```json
{
    "require-dev": {
        "squizlabs/php_codesniffer": "^2.7",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.2.1",
        "frenck/php-compatibility": "^7.1"
    },
    "scripts": {
        "post-install-cmd": [
            "# Running incenteev/composer-parameter-handler ...",
            "# Clearing cache...",
            "phpcs src"
        ]
    }
}
```

You would want to run `phpcs` on `post-install-cmd` but, on Gitlab CI, not the other commands?

**Comment by Potherca** [comment]
@frenck The most simple way I can think of is to expose the functionality of the plugin directly so it could be called as an (aliased) composer-script command. I've drafted a working example in PR #5.

The plugin could be triggered by the following `composer.json`:

```json
{
    "...": {
        "...": "..."
    },
    "scripts": {
        "codesniffer": [
            "phpcs src"
        ],
        "post-install-cmd": [
            "# Running incenteev/composer-parameter-handler ...",
            "# Clearing cache...",
            "@codesniffer"
        ],
        "run-codesniffer": [
            "Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin::run"
            "@codesniffer"
        ]
    }
}
```

That way,  `composer install --no-scripts` could be run to install all of the dependencies without triggering any composer-scripts. After that, `composer run-codesniffer` could be run to trigger the plugin and run the code-sniff<sup>1</sup>.

<sup><strong>1</strong></sup> Although that could also be done as a separate command in the build outside of the composer file).

Thoughts?

**Comment by Wirone** [comment]
We have standard scripts definition for Symfony project:

```json
{
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    }
}
```

And there is `gitlab-ci.yml` where under `before_scripts` section we have `composer install` (and other scripts). After composer install, when `Incenteev\\ParameterHandler\\ScriptHandler::buildParameters` is invoked (with non-interactive mode) all parameters from dist are saved to target config file, then `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache` clears the cache and raises an error if required parameters are missing or don't have valid value.

Your solution is perfect, I thought about something like that - ability to run `composer install --no-scripts` and then run only installation of PHPCodeSniffer standards.

For now we have mocked some parameters and polished Gitlab CI configuration so everything is working fine, but this functionality would be great anyway :-)

**Comment by Potherca** [comment]
This feature was discussed with @frenck and we're going to add it to the plugin. 

The plan is to add unit-tests once PR's #6 and #8 have been merged, after that my PR will be updated and this feature will be implemented.

**Comment by Potherca** [comment]
This has been fixed in PR #5, should be part of the upcoming release (see issue #11).

**Comment by Wirone** [comment]
Thank you very much, it works as expected :+1: 

Just as a note, this feature can be used like this:

```
{
    "scripts": {
        "install-php-compatibility-sniff": [
            "Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin::run"
        ],
        "post-install-cmd": [
            "@install-php-compatibility-sniff"
        ],
        "post-update-cmd": [
            "@install-php-compatibility-sniff"
        ]
    },
}
```

You can then use `composer run-script install-php-compatibility-sniff` at any moment.

Also in Gitlab CI's `before_script` you can install vendors with `--no-scripts` option and then install sniff in order to use PHPCS with PHPCompatibility.

**Comment by Potherca** [comment]
![Smiling Face](https://dealerdirect.github.io/Memes/img/png/happy.png)

Thanks for the feedback. I'll be sure to update the documentation (including an example).
