### ISSUE TITLE
Scan depth as parameter

### ISSUE THREAD

**Issue by alexdesignworks** [Dealerdirect/phpcodesniffer-composer-installer#45]
## Problem/Motivation
This is feature request.

Current scan depth is set to less then 4. This may not work for cases when `ruleset.xml` is provided in the package that contains multiple rulesets - such package would use additional parent directory to hold multiple rulesets.

Exposing scan depth to be extracted from `extra` section would allow more granular  per-project config.

**Comment by Potherca** [comment]
Thank you for taking the time to report this, my apologies for the slow response (we try to respond within a week).

I have opened a pull-request implemented this, if @frenck agrees with the implementation, I am not opposed to adding this feature.

**Comment by Potherca** [comment]
@frenck Ping?

**Comment by frenck** [comment]
This feature has been added @alexdesignworks, thanks to @Potherca!

Will be part of the next release.
