### ISSUE TITLE
PHPCS invocation fails on Windows 10 if installed globally

### ISSUE THREAD

**Issue by jonathanjfshaw** [Dealerdirect/phpcodesniffer-composer-installer#50]
## Problem/Motivation
Running composer update in a project fails on Windows 10 when this plugin is installed globally.

## Error

```
  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command ""C:\users\jonathan\drupal\behatdrupal/vendor/bin\phpcs" "--config-show" "installed_paths"" failed.
  Exit Code: 1(General error)
  Working directory: C:\users\jonathan\drupal\behatdrupal
  Output:
  ================
  Error Output:
  =
===============
  '"C:\users\jonathan\drupal\behatdrupal/vendor/bin\phpcs"' is not recognized as an internal or external command,
  operable program or batch file.

```

**Comment by frenck** [comment]
Not sure why this is handled differently on Window.
I personally do not have access to Windows machines, so this needs to be solved/triaged by external contributors.

**Comment by jonathanjfshaw** [comment]
Sorry, no, I don't have a suitable working composer setup

**Comment by Potherca** [comment]
I'll have a look at this soonish, together with #79 and #80.

**Comment by Potherca** [comment]
Version [v0.6.0](https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.6.0) has just been released. Besides several fixes, this version also adds improved debug/verbose output.

@jonathanjfshaw  Could you try to reproduce the issue you reported with `v0.6.0` and let us know if it still happens? If so, please run the plugin in verbose mode and paste the output of the run here (that should make it possible for us to re-produce the issue ourselves).

**Comment by jrfnl** [comment]
@jonathanjfshaw Any feedback ? I would love to know if this is still an issue or if this can be closed.

**Comment by jonathanjfshaw** [comment]
Sorry, I'm no longer using composer on Windows 10 so can't retest.

**Comment by Potherca** [comment]
As luck would have it, I now have access to a Windows 10 machine (we've had to buy a family computer to keep up with all the video meetings the children have for school).

My current timetable would allow me to take a look at this the coming weekend. I'll post my findings as soon as I've run throught things. 👍

**Comment by Potherca** [comment]
I've finally gotten round to running this on a Windows machine.

Both powershell and regular shell give me no trouble with a global install present.

Closing this as it can not be reproduced.
