### ISSUE TITLE
Getting a new stable release

### ISSUE THREAD

**Issue by dalibor-matura** [Dealerdirect/phpcodesniffer-composer-installer#60]
## Problem/Motivation

There wasn't a stable release for almost a year and we would really like to use the fix from commit https://github.com/mickaelperrin/phpcodesniffer-composer-installer/commit/698b12467f15a6d4bbacddbce14d43b69d795df6, but composer requirements/restrictions are not going to allow us to use `master-dev` verson of this package.

The commit (`master` branch) holds a fix https://github.com/Dealerdirect/phpcodesniffer-composer-installer/pull/51 for this https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/49#issuecomment-403832708

## Expected behaviour & Proposed change

Have a new stable release 0.4.5 (or 0.5.0) with all the fixes we could update to.

Obviously it needs to be reviewed first.

## Actual behaviour

There a lot of commits in `master` branch after the last stable version 0.4.4 was released.

It is possible that a good number of people can not use these fixes because composer setup on their project doesn't allow to use unstable version of the package.

**Comment by Potherca** [comment]
If @frenck agrees, I would like to add #51, #54, #60 and #62 and tag a new release `v0.5.0`.

**Comment by frenck** [comment]
This issue is mainly a request and not an issue. A new release will follow soon, closing this issue, because it isn't an issue.
