### ISSUE TITLE
Install Plugin provides no feedback

### ISSUE THREAD

**Issue by christopher-hopper** [DealerDirect/phpcodesniffer-composer-installer#7]
## Problem/Motivation

After running a Composer install or update there is nothing in the command output to show what was changed (or not changed) by this installer plugin. 

## Expected behaviour

Composer will output the PHP CodeSniffer configuration key and value that it has set or changed.

## Actual behaviour

Nothing is shown to even indicate whether this Composer Plugin for PHP CodeSniffer was executed or not. If a PHP CodeSniffer configuration is changed, Composer does not say so.

## Steps to reproduce

1. Require this package with a supported standards package as per the README instructions.
1. Execute `composer install` or `composer update`

## Proposed changes

Use the Composer IO to write to output: 

1. Something to say the Plugin has started or is being run.
1. The config key and value to be set in PHP CodeSniffer.
1. (Optional) The results of the PHP CodeSniffer command to set a configuration key (ie. result from `vendor/bin/phpcs --config-set key value`)

**Comment by Potherca** [comment]
I'm in favour of this.

**Comment by frenck** [comment]
This is a major improvement! Thanks for creating this issue and even more thanks for the PR!

For the future it would be even more awesome if we could display the actual ruleset names instead of paths.

**Comment by frenck** [comment]
Merged, thank you for this PR!
