### ISSUE TITLE
Add @jrfnl as (co)maintainer to this project

### ISSUE THREAD

**Issue by Potherca** [Dealerdirect/phpcodesniffer-composer-installer#87]
Currently, besides myself, only @frenck and @mjrider are active (co)maintainers of this project.
As all three of us have other responsibilities (both towards other code-projects as in our private lives), we are often not able to respond to issues in this project in a timely fashion.

In order to make sure this project remains relevant _and_ active, I suggest we need to add a (co)maintainer who is more available.

After reaching out to through other media, @jrfnl agreed to offer this project support.

I would suggest someone whom has sufficient privileges adds @jrfnl to the correct roles in this project.

**Comment by mjrider** [comment]
Done

**Comment by jrfnl** [comment]
Not sure whether I'll be "_more available_" as I also have plenty of other commitments, but between the four of us, we'll hopefully be able to move some issues forward.
